jenkins:
  systemMessage: "Jenkins configured automatically by JCasC"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
      - name: "sonarqube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonarqube-token-new"

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "sonarqube-token-new"
              secret: "${SONAR_TOKEN}"
              description: "SonarQube authentication token"

jobs:
  - script: >
      pipelineJob('petclinic-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url(System.getenv('GIT_REPO_URL') ?: '')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
